---
title: "EGT204: EĞİTİMDE ARAŞTIRMA YÖNTEMLERİ"
subtitle: "Ders Iceriği"
date: "Guz - 2024"
output:
  html_document:
    toc: true
    toc_depth: 2
    toc_float: true
    theme:  default
    highlight: null
    css: styles.css
---
```{r include=FALSE}
options(scipen=999)
library(tidyverse)
library(stevemisc)
#library(ggpmisc)
#library(anonymizer)
# library(ggcal)
#library(stringr)
#library(kfigr)
#library(broom)
library(lubridate)
advdate <- function(obj, adv) {
 tmon <- obj + 7*(adv-1)
 # tfri <- obj + 4 + 7*(adv-1)
 tmon <- format(tmon, format="%d/%m")
 # tfri <- format(tfri, format="%d/%m")
 zadv <- sprintf("%02d", adv)
 tmp <- paste("Hafta ",zadv,sep='',", ", tmon)
 return(tmp)
}
mon <- ymd(20241004)

```

------------------------------------------------------------------------

|                                        |                                |
|----------------------------------------|--------------------------------|
| **email:** kkatalay\@gmail.com         |  katalay@hacettepe.edu.tr |
                | **Sinif:** B9Z03             |
| **Ofis saatleri:** Cuma 10:00-12:00    | **Saat:**  10:40-12:30         |
| **Ofis:** "Eğitim Bilimleri Enstitüsü" |                                |


# Ders Amacı

Öğrencilere eğitimde araştırma yöntemlerini tanıtmak, araştırma sürecinde problem belirlemek, probleme uygun araştırma modelini seçmek, evreni ve örneklemi belirlemek, veri toplamak ve veri analizi, analiz sonuçlarını yorumlamak, araştırma sonuçlarını rapor etmek ve araştırma ilkelerine ve etiğine uyma konularında bilgi ve beceri sahibi olmalarını sağlamaktır.

# Ders Hedefleri

Bu dersi başarıyla tamamlayan öğretmen adayları ders bitiminde aşağıdaki hedeflenen kazanımları edinmiş olur:

1.  Araştırma yöntemleriyle ilgili temel kavramları ve ilkeleri tanımlar.

2.  Araştırma problemlerini belirleyerek probleme uygun araştırma modelini seçer, evreni ve örneklemi belirler.

3.  Araştırma modeline uygun veri toplama araçları ile veri toplar, veriyi analiz eder, analiz sonuçlarını yorumlar.

4.  Araştırma ilkelerine ve etiğine uygun araştırma raporu hazırlar.

# Ders İşlenişi

Dersler "Ders Planı" başlığı altındaki sıralamaya göre işlenecektir. Belirtilen başlık altında her haftanın ilgili ders dokumanına bağlantı sunulmuştur.

# Notlandırma


-   `r emo::ji("notebook")`  **50% Derse Katılım ve Ödevler**
    - Ödev I  - 10 puan - problem durumu bulma
    - Ödev II - 10 puan - araştırma problemi inceleme
-   `r emo::ji("notebook")` **50% Genel Sınav**

- `r emo::ji("warning")`  Ders sonunda hazırladığınız proje ile 
`r emo::ji("link")`[TUBITAK 2209-A - Üniversite Öğrencileri Araştırma Projeleri Destekleme Programı'na başvurabilirsiniz.](https://www.tubitak.gov.tr/tr/burslar/lisans/burs-programlari/icerik-2209-a-universite-ogrencileri-arastirma-projeleri-destekleme-programi)

# Okuma Listesi

-   `r emo::ji("book")` Büyüköztürk, Ş., Çakmak E. K., Akgün, Ö. E., Karadeniz, Ş., Demirel, F. (2020). Eğitimde Bilimsel Araştırma Yöntemleri (28. Baskı), Pegema Yayıncılık.

-   `r emo::ji("book")`Ocak, G. (2019). Eğitimde Bilimsel Araştırma Yöntemleri. Pegema Yayıncılık.

- `r emo::ji("book")` Arık, R. S. ve Yılmaz, K. (2019). Eğitimde Bilimsel Araştırma Yöntemleri. Pegema Akademi.

-   `r emo::ji("book")` Çetin, B., İlhan, M. ve Şahin, M. G. (2021). Eğitimde Araştırma Yöntemleri: Temel Kavramlar, İlkeler ve Süreçler, Pegem Akademi.

-   `r emo::ji("book")` Frankel, J. R.; Wallen, N. E. & Hyun, H. H. (2012). How to Design and Evaluate Research in Education (8th Edition). McGraw Hill International.

-   `r emo::ji("book")` Creswell, J. W. (2012) Educational Research Planning, Conducting and Evaluating Quantitative and Qualitative Research (4th Edition). Pearson Education.

- `r emo::ji("paper")` Aydın, A., Sarıer, Y., & Uysal, Ş. (2012). Sosyoekonomik ve Sosyokültürel Değişkenler Açısından PISA Matematik Sonuçlarının Karşılaştırılması. Eğitim ve Bilim, 37(164), 20-29 . http://eb.ted.org.tr/index.php/EB/article/view/219/360 adresinden erişildi. 


```{=tex}
\clearpage
\newpage
```
# Ders Planı

* belirtilen tarihlerde değişiklikler olabilir.
sizlere gelen bildirimleri takip ediniz.

## `r advdate(mon, 2)`:[Bilimsel Araştırma Temel Kavramlar](sunum/01_temeller.html)

-   Bilgi Nedir? Bilgi Edinme Yolları Nelerdir?
-   Bilim Nedir?
-   Bilimin Temel İşlevleri
-   Bilimin Başlıca Özellikleri

## `r advdate(mon, 3)`: Araştırma Problemin Tanımlanması 

- [Probleminin Tanımlanması I](sunum/ProblemI.html)
  -   İyi bir araştırma probeliminin sahip olması gereken özellikler
  -   Problem ve alt problemler
  -   Literatur Taraması
- [Probleminin Tanımlanması II](sunum/ProblemII.html)
  -   Değişken nedir?
  -   Değişken Sınıflaması
  -   Hipotez Nedir?
  -   Hipotez Türleri
  -   Araştırma Amacı ve Önemi
  -   Sayıltı ve Sınırlılık
  -   Tanımlar, Kısaltmalar

=> ODEV I - 10 puan


## `r advdate(mon, 4)`:[Ölçmede Temel Kavramlar](sunum/olcme.html)
-   Ölçme Nedir?
-   Ölçüm Nedir?
-   Ölçek Nedir?
-   Ölçek Türleri
-   Ölçmede Hata
-   Ölçme Aracının Sahip Olması Gereken Özellikler
-   Korelasyon

=> ODEV II - 10 puan

## `r advdate(mon, 5)`: [Örnekleme Yöntemleri](sunum/ornekleme.html)


-   Evren - Örneklem Tanımı Örnekleme Nedir?
-   Örnekleme Yöntemleri
-   Örnekleme Aşamaları
-   Örneklem Büyüklüğü
-   Örnekleme Hatası

## `r advdate(mon, 6)`: [Veri Toplama Araçları I](sunum/VeriToplama-nicel.html)

- Veri Toplama Araçları
- Anket
- Anket Geliştirme Süreci
- Madde Türleri
- Ölçekler

## `r advdate(mon, 9)`:[Veri Toplama Araçları II](sunum/Veritoplama-nitel.html)

-   Anketler
-   Gözlem formları
-   Görüşme formları
-   Çevirim için veri toplama araçları


## `r advdate(mon, 10)`: [Nicel Araştırmalar I](sunum/Nicel.html)

-   İç geçerlik - Dış Geçerlik
-   Tarama Araştırması
-   Korelasyon Araştırması


## `r advdate(mon, 11)`: [Nicel Araştırmalar II](sunum/Deneysel.html)

-   Nedensel Araştırma
-   Deneysel Araştırmalar ve Türleri

## `r advdate(mon, 12)`: [Nitel Araştırmalar I](sunum/Nitel.html)

-   Nicel ve Nitel Araştırma Farkları
-   Nitel Araşatırma Aşamaları
-   Karma Desenler
-   İçerik Analizi
-   Eylem Araştırması
-   Durum Araştırması

## `r advdate(mon, 13)`: [Verilerin Analizi](sunum/Verianaliz.html)

-   Parametre Nedir?
-   İstatistik Nedir?
-   Nitel Veriler
-   Nicel Veriler
-   Nicel Veri Özetleme Teknikleri
-   Merkezi Eğilim ve Dağılım Ölçüleri
-   Korelasyon Frekans Tablosu ve Grafikler




## `r advdate(mon, 14)`: [Araştırma Raporu Hazırlama, Araştırma ve Yayın Etiği](sunum/Raporhazirlama.html)

-   Rapor hazırlamada dikkat edilecek hususlar
-   Araştırma türlerine göre rapor örnekleri
-   Araştırma raporu bölümleri
-   Etik Nedir?
-   Bilim Etiğinin Temel İlkeleri

## `r advdate(mon, 15)`: Genel Sınav






